#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.4.15f1_fbf367ac14e9"
#define UNITY_VERSION_FULL_NICE "2019.4.15f1 (fbf367ac14e9)"
#define UNITY_VERSION_BLD 16511847
#define UNITY_VERSION_DATE 1605224406
#define UNITY_VERSION_WIN "2019.4.15.16511847"
#define UNITY_VERSION_BRANCH "2019.4/release"
